:: CQT_Run_Custom_Test.bat
:: Template batch file to run custom testing routines.
:: USAGE: Set the two variables below, save as .bat into the same folder as the CQT .exe, and then double click the .bat file.

@echo off

:: The CQT .exe file to use (batch file must be in same folder)
set CQT_EXE=CameraQuickTester.exe
:: Example of using the CQT commandline arguments
set CQT_ARGS=-help

:: Available CQT commandline arguments:
::
:: GENERAL OPTIONS:
::  -serialnumber 12345678                  Specify the camera to test via serial number.
::  -wipecamera                             After testing, wipe all non-volatile memory and return camera to factory state.
::  -rebootcamera 10                        After successful detection, the camera can be rebooted and reconnected this many times (default is no reboot).
::  -reboottype 1                           1=DeviceReset node (default), 2=disable/enable Camera in Device Manager, 3=disable/enable USB Composite Device in DevMgr.
::  -reconnecttimeoutsec 10                 How many seconds we should try to reconnect a camera that has lost connection during testing (or by -rebootcamera).
::  -unknownusbcheck                        Check if any USB devices are detected by the OS as "Unknown".
::  -unknownusbfix                          Experimental. Try to fix any "Unknown" USB devices by disabling & re-enabling the device and/or its parent device.
::  -detectionattempts 30                   How many times we will intially try to detect a camera before giving up.
::  -findipfrommac AA:BB:CC:DD:EE:FF        If GigE camera detection fails, try to at least find the IP address of the camera by using its MAC address.
::  -ping 192.168.123.456                   If GigE camera detection fails, try to Ping the camera if the IP address is known.
::  -keepfiles                              Keep all raw files generated by the CQT in addition to adding them to the zip (by default these are deleted after zipping.)
::  -help                                   Shows this menu.
::
:: CONTINUOUS IMAGE GRAB TEST OPTIONS:
::  -resultstograb 500                      Number of Grab Results to retrieve (may or may not contain a valid image).
::  -grabtimesec 10                         Use instead of -resultstograb. How long we should grab images in seconds.
::  -buffers 100                            Number of buffers the Grab Engine should use (default = 100 MB / payloadsize).
::  -buffermemorymb 100                     Use instead of -buffers. Grab Engine will make as many buffers as possible from this amount of memory (default = 100 MB).
::  -failstoaccept 3                        Number of Grab Results marked as Failed, timeouts, or combination of, to accept before aborting test.
::  -grabtimeoutmsec 10000                  How long in milliseconds we should wait for an image to arrive before timing out.
::  -overridepfs mysettings.pfs             Override default settings with a .pfs file (use -overridepfs current to use the camera's current pre-test settings).
::  -overridesingle GevSCPSPacketSize 1500  Override a single camera setting by specifiying feature name and desired value.
::  -usetestimage                           Use the camera's test image instead of live image.
::  -displayimages                          Display images during test. This may reduce performance and lead to buffer underruns (dropped frames).
::  -delayedretrieval                       Collect all Grab Results in Grab Engine first, THEN retrieve them. Uses A LOT of memory (does not recycle buffers)!

IF EXIST "%CQT_EXE%" (
START %CQT_EXE% %CQT_ARGS% EXIT
) ELSE (
goto :filenotfound
)
EXIT

:filenotfound
ECHO %CQT_EXE% Not found.
ECHO Please place this batch file in the same folder as %CQT_EXE%.
PAUSE